import Head from "next/head";
import { Inter } from "next/font/google";
import { useEffect, useState } from "react";
import axios from "axios";
import Link from "next/link";

export default function Home() {
  const [data, setData] = useState([]);
  const len = data.length;
  useEffect(() => {
    axios
      .get("http://localhost:3004/users")
      .then((response) => setData(response.data))
      .catch((error) => console.log(error));
  }, []);

  const handleDelete = (id) => {
    const confirm = window.confirm("Are you sure of this operation");
    if (confirm) {
      axios
        .delete("http://localhost:3004/users/" + id)
        .then((res) => location.reload())
        .catch((err) => console.log(err));
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <span>{len} Users Added</span>
        <Link href="/Create">
          <button className="add-btn">add +</button>
        </Link>
      </div>
      <table className="users-data">
        <thead>
          <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Email</th>
            <th>Phone No</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          {data.map((d) => {
            return (
              <tr key={d.id}>
                <td>{d.id}</td>
                <td>{d.name}</td>
                <td>{d.email}</td>
                <td>{d.phone}</td>
                <td className="td-btn">
                  <Link href={`/Update/${d.id}`}>
                    <button className="btn-sub">edit</button>
                  </Link>
                  <Link href={`/Read/${d.id}`}>
                    <button className="btn-sub">read</button>
                  </Link>

                  <button
                    onClick={() => handleDelete(d.id)}
                    className="btn-sub"
                  >
                    delete
                  </button>
                </td>
              </tr>
            );
          })}
        </tbody>
      </table>
    </>
  );
}
