import Head from "next/head";
import { useEffect, useState } from "react";
import axios from "axios";
import Link from "next/link";
import { RiDeleteBinLine } from "react-icons/ri";
import { BiEditAlt } from "react-icons/bi";
import { BsPersonAdd, BsFillTelephoneInboundFill } from "react-icons/bs";
import { AiOutlineMail } from "react-icons/ai";
import { SiGithubactions, SiNamecheap } from "react-icons/si";
export default function Home() {
  const [data, setData] = useState([]);

  //Fetch Data From db.json File
  useEffect(() => {
    axios
      .get("http://localhost:3004/users")
      .then((response) => setData(response.data))
      .catch((error) => console.log(error));
  }, []);

  //Delete Data
  const handleDelete = (id) => {
    const confirm = window.confirm("Are you sure of this operation");
    if (confirm) {
      axios
        .delete("http://localhost:3004/users/" + id)
        .then((res) => res)
        .catch((err) => console.log(err));
    }
    const deleteItem = data.filter((d, i) => d.id !== id);
    setData(deleteItem);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <Link href="/create">
          <button className="add-btn">
            <BsPersonAdd />
          </button>
        </Link>
      </div>
      <table className="users-data">
        <thead>
          <tr>
            <th>Id</th>
            <th>
              Name <SiNamecheap className="datas-icon" />
            </th>
            <th>
              Email
              <AiOutlineMail className="datas-icon" />
            </th>
            <th>
              Phone No <BsFillTelephoneInboundFill className="datas-icon" />
            </th>
            <th>
              Actions <SiGithubactions className="datas-icon" />
            </th>
          </tr>
        </thead>
        <tbody>
          {data.map((d) => (
            <tr key={d.id}>
              <td>{d.id}</td>
              <td>{d.name}</td>
              <td>{d.email}</td>
              <td>{d.phone}</td>
              <td className="td-btn">
                <Link href={{ pathname: "/read", query: { id: d.id } }}>
                  <button className="btn-sub">Read</button>
                </Link>
                <Link href={{ pathname: "/update", query: { id: d.id } }}>
                  <button className="btn-sub">
                    <BiEditAlt />
                  </button>
                </Link>

                <button onClick={() => handleDelete(d.id)} className="btn-sub">
                  <RiDeleteBinLine />
                </button>
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </>
  );
}
